### ISSUE TITLE
Jetbrains IDEs support

### ISSUE THREAD

**Issue by PatMyron** [JuliaEditorSupport/roadmap#12]
Might help to partner with this existing plugin:

https://plugins.jetbrains.com/plugin/10413-julia
https://github.com/ice1000/julia-intellij

**Comment by s-celles** [comment]
Maybe we should have a minimal repository under [JuliaEditorSupport Github organization](https://github.com/JuliaEditorSupport/ ) to show how to install plugin for Julia support in Jetbrains IDEs.

An other option might be to move [`ice1000/julia-intellij` repository](https://github.com/ice1000/julia-intellij) here if @ice1000, @zxj5470 and [others julia-intellij contributors](https://github.com/ice1000/julia-intellij/graphs/contributors) accept such an idea (obviously he/they will be granted commit rights in the new repository like in the original repository).

A last option could be to fork (instead of moving) [repository](https://github.com/ice1000/julia-intellij). As the previous option, this option have only interest if [`ice1000/julia-intellij`](https://github.com/ice1000/julia-intellij) contributors want to contribute under [JuliaEditorSupport](https://github.com/JuliaEditorSupport/) organization name.

My personal opinion, is that having julia-intellij under [JuliaEditorSupport](https://github.com/JuliaEditorSupport) will give more highlight to both Jetbrains IDE and this Julia plugin.

But that's just my opinion.

**Comment by ice1000** [comment]
Agreeing with transfering the repo.

But I need at least member access to this org.

**Comment by ice1000** [comment]
Interestingly, I didn't see anyone contacting me for "partner with this existing plugin" 🙃

**Comment by s-celles** [comment]
Thanks @ice1000 for accepting the idea of transferring your repository.

According Github when creating an invite to an org, we can see:

    Members can see all other members, and can be granted access to repositories. 
    They can also create new teams and repositories.

Does it means that you will get commit rights to all repositories of JuliaEditorSupport?

If so I think I should first ask opinion of others members of https://github.com/JuliaEditorSupport/ (especially those with owner access).

    Owners have full administrative rights to the organization 
    and have complete access to all repositories and teams.

Sorry but I didn't understand your second post (I'm not an english speaker... so I may have missed something)

**Comment by ice1000** [comment]
Well please ignore the second post. For the first question I'll say there's two kinds of org member: "member" and "owner". Owners are admins, members are admin to the repositories that they have access to, or the team they belong to have access to. The access is granted by admins.
So no worries about inviting me as a member will give me unnecessary rights.

**Comment by s-celles** [comment]
Hi @ice1000 , I've just send you an invite to JuliaEditorSupport as member.

**Comment by s-celles** [comment]
Julia Plugin for IntelliJ IDEA is available now at
https://github.com/JuliaEditorSupport/julia-intellij
Thanks @ice1000 for the great work
